run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - gocyclo

  linters-settings:
    gocyclo:
      min-complexity: 50 # 如果一个函数的圈复杂度超过 15，就会报错 (建议拆分函数)
    errcheck:
      check-type-assertions: true
      check-blank: true

  issues:
    exclude-use-default: false
    max-issues-per-linter: 0
    max-same-issues: 0